version: "3"
services:
    react:
        container_name: docker-react-mongo
        restart: always
        build: ./frontend
        ports:
            - '70:3000'
        links:
            - node
    node:
        container_name: docker-node-mongo
        restart: always
        build: ./backend
        ports:
            - '90:5000'
        links:
            - mongo
        environment:
          NODE_ENV: "${NODE_ENV}"
          PORT: "${PORT}"
          MONGO_URI: "${MONGO_URI}"
          JWT_SECRET: "${JWT_SECRET}"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'

